local_backend: true
backend:
  name: github
  repo: mingshanlu/mixhub
  branch: main # Branch to update (optional; defaults to master)

# 設定介面語系為繁體中文
locale: 'zh_Hant'    

# publish_mode: editorial_workflow
media_folder: "source/images/uploads"
public_folder: "images/uploads"
#relative_path: true

# This also works, but it's deprecated. Same as logo.src
logo_url: ../images/logo.png

collections :
  - name: "blog"
    label: "MIXHUB 文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string", required: true }
      - { label: "類型", name: "type", widget: "select", options: ["tags", "categories", "link"], required: true }
      - { label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: true }
      - { label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "分類", name: "categories", widget: "string", required: false }
      - { label: "頁面頂部圖片", name: "top_img", widget: "image", required: false }
      - { label: "封面圖", name: "cover", widget: "image", required: false }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "關鍵字", name: "keywords", widget: "string", required: false }
      - { label: "內文", name: "body", widget: "markdown", required: false }
      - { label: "排序方式", name: "orderby", widget: "select", options: ["random", "name", " length"], required: false }
      - { label: "排序次序", name: "order", widget: "select", options: [1, -1], required: false }
      - { label: "顯示文章版權模塊", name: copyright", widget: "boolean", default: true, required: false }   
      - { label: "文章版權作者", name: "copyright_author", widget: "string", required: false }
      - { label: "文章版權作者鏈接", name: "copyright_author_href", widget: "string", required: false }
      - { label: "文章版權連結", name: "copyright_url", widget: "string", required: false }
      - { label: "文章版權信息", name: "copyright_info", widget: "string", required: false }
      - { label: "留言區塊顯示", name: "comments", widget: "boolean", default: false, required: false }
      - { label: "顯示 mathjax", name: "mathjax", widget: "boolean", default: false, required: false }
      - { label: "顯示 katex", name: "katex", widget: "boolean", default: false, required: false }
      - { label: "加載 abcjs", name: "abcjs", widget: "boolean", default: false, required: false }
      - { label: "顯示側邊欄", name: "aside", widget: "boolean", default: true, required: false }
      - { label: "加載音樂播放器", name: "aplayer", widget: "boolean", default: false, required: false }
      - { label: "配置原始碼框是否展開", name: "highlight_shrink", widget: "boolean", default: false, required: false }
      - { label: "友情鏈接是否隨機排序", name: "random", widget: "boolean", default: false, required: false }
      - { label: "説説顯示數量", name: "limit", widget: "number", required: false }
      - { label: "説説顯示數量", name: "limit.type", widget: "select", options: ["date", "num"], required: false }
      - { label: "説説顯示數量的值", name: "limit.value", widget: "string", required: false }
      - { label: "顯示文章 TOC", name: "toc", widget: "boolean", default: false, required: false }
      - { label: "顯示文章 TOC NUMBER", name: "toc_number", widget: "number", required: false }
      - { label: "顯示 TOC 簡潔模式", name: "toc_style_simple", widget: "boolean", default: false, required: false }
      - { label: "文章過期提醒", name: "noticeOutdate", widget: "boolean", default: false, required: false }
